# This is a basic workflow to help you get started with Actions

name: sync-to-gitee

# Controls when the workflow will run
on:
  push:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  repo-sync:
    env:
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
      dst_token: ${{ secrets.GITEE_TOKEN }}
      #gitee_user: ${{ secrets.GITEE_USER }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout
        
      - name: sync to gitee
        uses: Yikun/hub-mirror-action@master
        if: env.dst_key && env.dst_token
        with:
          src: 'github/${{ github.repository_owner }}'
          dst: 'gitee/${{ github.repository_owner }}'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          # 如果是组织，指定组织即可，默认为用户 user
          # account_type: org
          static_list: ${{ github.event.repository.name }}
          force_update: true
